name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
  IMAGE_NAME: ${{ secrets.DOCKER_REGISTRY_IMAGE }}-webhost
  ASPNETCORE_ENVIRONMENT: "Production"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker Registry
      run: echo "${{ secrets.DOCKER_REGISTRY_PASSWORD }}" | docker login ${{ secrets.DOCKER_REGISTRY }} -u ${{ secrets.DOCKER_REGISTRY_USER }} --password-stdin
    
    - name: Build and push Docker image
      run: |
        docker build -t $IMAGE_NAME:${{ github.ref_name }} -f PromoCodeFactory.WebHost/Dockerfile .
        docker push $IMAGE_NAME:${{ github.ref_name }}

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Run unit tests
      run: dotnet test

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Login to Docker Registry
      run: echo "${{ secrets.DOCKER_REGISTRY_PASSWORD }}" | docker login ${{ secrets.DOCKER_REGISTRY }} -u ${{ secrets.DOCKER_REGISTRY_USER }} --password-stdin
    
    - name: Deploy application
      run: |
        docker pull $IMAGE_NAME:${{ github.ref_name }}
        docker tag $IMAGE_NAME:${{ github.ref_name }} $IMAGE_NAME:latest
        docker push $IMAGE_NAME:latest