stages:
  - build
  - test
  - deploy

variables:
  DOCKER_REGISTRY: $CI_REGISTRY
  IMAGE_NAME: ${CI_REGISTRY_IMAGE}-webhost
  ASPNETCORE_ENVIRONMENT: "Production"

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - echo "Building PromoCodeFactory.WebHost image..."
    - docker build -t $IMAGE_NAME:$CI_COMMIT_REF_SLUG -f PromoCodeFactory.WebHost/Dockerfile .
    - docker push $IMAGE_NAME:$CI_COMMIT_REF_SLUG
  tags:
    - docker

test:
  stage: test
  script:
    - echo "Running unit tests..."
    - dotnet test
  tags:
    - docker

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    - docker pull $IMAGE_NAME:$CI_COMMIT_REF_SLUG
    - docker tag $IMAGE_NAME:$CI_COMMIT_REF_SLUG $IMAGE_NAME:latest
    - docker push $IMAGE_NAME:latest
  environment:
    name: production
    url: https://your-production-url.com
  only:
    - main
  tags:
    - docker

cache:
  paths:
    - PromoCodeFactory.WebHost/bin/
    - PromoCodeFactory.WebHost/obj/
