name: CI/CD Конвейер

# Триггеры запуска
on:
  push:
    branches: [ main ]  # Запускать при пуше в main
  pull_request:
    branches: [ main ]  # И при пул-реквестах в main

# Общие переменные
env:
  DOCKER_REGISTRY: ${{ secrets.CI_REGISTRY }}
  IMAGE_NAME: ${{ secrets.CI_REGISTRY_IMAGE }}-webhost
  ASPNETCORE_ENVIRONMENT: "Production"

jobs:
  build:
    runs-on: ubuntu-latest  # Запускать на Ubuntu
    steps:
    - uses: actions/checkout@v3  # Получить код
    - name: Вход в Docker Registry
      run: docker login -u ${{ secrets.CI_REGISTRY_USER }} -p ${{ secrets.CI_REGISTRY_PASSWORD }} ${{ secrets.CI_REGISTRY }}
    - name: Сборка Docker-образа
      run: |
        echo "Собираем образ PromoCodeFactory.WebHost..."
        docker build -t $IMAGE_NAME:${{ github.ref_name }} -f PromoCodeFactory.WebHost/Dockerfile .
        docker push $IMAGE_NAME:${{ github.ref_name }}

  test:
    runs-on: ubuntu-latest
    needs: build  # Зависит от этапа build
    steps:
    - uses: actions/checkout@v3
    - name: Запуск unit-тестов
      run: dotnet test  # Запуск тестов .NET

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]  # Ждёт завершения build и test
    if: github.ref == 'refs/heads/main'  # Только для ветки main
    steps:
    - name: Развертывание приложения
      run: |
        echo "Развертываем приложение..."
        docker pull $IMAGE_NAME:${{ github.ref_name }}
        docker tag $IMAGE_NAME:${{ github.ref_name }} $IMAGE_NAME:latest
        docker push $IMAGE_NAME:latest
    - name: Установка URL окружения
      run: echo "DEPLOYMENT_URL=https://ваш-продакшен-сайт.com" >> $GITHUB_ENV
