name: CI/CD Конвейер

# Триггеры запуска
on:
  push:
    branches: [ main ]  # Запускать при пуше в main
  pull_request:
    branches: [ main ]  # И при пул-реквестах в main

# Общие переменные
env:
  DOCKER_REGISTRY: ${{ secrets.CI_REGISTRY }}
  IMAGE_NAME: ${{ secrets.CI_REGISTRY_IMAGE }}-webhost
  ASPNETCORE_ENVIRONMENT: "Production"

jobs:
  build:
    runs-on: ubuntu-latest  # Запускать на Ubuntu
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./Homeworks/UnitTests/src/PromoCodeFactory.sln
    - name: Build
      run: dotnet build ./Homeworks/UnitTests/src/PromoCodeFactory.sln --no-restore
    - name: Test
      run: dotnet test ./Homeworks/UnitTests/src/PromoCodeFactory.UnitTests/PromoCodeFactory.UnitTests.csproj --no-restore --logger "console;verbosity=detailed"
